export enum MaterialIcon {
  MENU = 'menu',
  SEARCH = 'search',
  CHAT = 'chat',
  ARROW_BACK = 'arrow_back',
  CLOSE = 'close',
  HOME = 'home',
  SETTINGS = 'settings',
  PERSON = 'person',
  FAVORITE = 'favorite',
  ADD = 'add',
  REMOVE = 'remove',
  EDIT = 'edit',
  DELETE = 'delete',
  CHECK = 'check',
  NOTIFICATIONS = 'notifications',
  LOCATION_ON = 'location_on',
  SHARE = 'share',
  INFO = 'info',
  WARNING = 'warning',
  ERROR = 'error',
}
